insert into white_card (text) values ('En sigøjner-forbandelse. ');
insert into white_card (text) values ('Et øjebliks stilhed. ');
insert into white_card (text) values ('En pølsefestival. ');
insert into white_card (text) values ('En ærlig betjent som intet har at miste. ');
insert into white_card (text) values ('Hungersnød. ');
insert into white_card (text) values ('Kødædende bakterier. ');
insert into white_card (text) values ('Flyvende sexslanger. ');
insert into white_card (text) values ('At ikke give en skid for den Tredje Verden. ');
insert into white_card (text) values ('Telefonsex. ');
insert into white_card (text) values ('Formskiftere. ');
insert into white_card (text) values ('Pornostjerner. ');
insert into white_card (text) values ('At Plyndre og Voldtage. ');
insert into white_card (text) values ('72 jomfruer. ');
insert into white_card (text) values ('En drive-by shooting. ');
insert into white_card (text) values ('Et tidsrejse-paradox. ');
insert into white_card (text) values ('Autentisk mexicansk mad. ');
insert into white_card (text) values ('Bling. ');
insert into white_card (text) values ('Konsulenter. ');
insert into white_card (text) values ('Ødelæggende gæld. ');
insert into white_card (text) values ('Far-problemer. ');
insert into white_card (text) values ('Mærsk McKinney Møllers Godkendelses-stempel. ');
insert into white_card (text) values ('At lade en lysekrone falde på dine fjender og ride på rebet opad. ');
insert into white_card (text) values ('George W. Bush. ');
insert into white_card (text) values ('Fuld frontal nøgenhed. ');
insert into white_card (text) values ('Hormon-injektioner. ');
insert into white_card (text) values ('Æglægning. ');
insert into white_card (text) values ('At tage alt tøjet af og se Nickelodeon. ');
insert into white_card (text) values ('At lade som om man er interesseret. ');
insert into white_card (text) values ('Offentlig ydmygelse. ');
insert into white_card (text) values ('Kanyle-deling. ');
insert into white_card (text) values ('Bussemænd. ');
insert into white_card (text) values ('Universets uundgåelige varmedød. ');
insert into white_card (text) values ('Barnefødslens mirakel. ');
insert into white_card (text) values ('Bortrykkelsen. ');
insert into white_card (text) values ('At hive den frem. ');
insert into white_card (text) values ('Hvidt privilegium. ');
insert into white_card (text) values ('Hustrupligter. ');
insert into white_card (text) values ('Axe kropsdeodorant. ');
insert into white_card (text) values ('Jesu Kristi blod. ');
insert into white_card (text) values ('Skræmmende laser-hårfjernings uheld. ');
insert into white_card (text) values ('Batman! ');
insert into white_card (text) values ('Landbrug. ');
insert into white_card (text) values ('En robust mongol. ');
insert into white_card (text) values ('Naturlig selektion. ');
insert into white_card (text) values ('Tøjbøjle-aborter. ');
insert into white_card (text) values ('At spise alle spejdernes småkager. ');
insert into white_card (text) values ('Michelle Obamas arme. ');
insert into white_card (text) values ('World of Warcraft. ');
insert into white_card (text) values ('Styrtdykning. ');
insert into white_card (text) values ('Overvægt. ');
insert into white_card (text) values ('En homoerotisk volleyball-film. ');
insert into white_card (text) values ('Låsekæbe. ');
insert into white_card (text) values ('Parringsfremvisning. ');
insert into white_card (text) values ('Stramninger i testis. ');
insert into white_card (text) values ('En rejebuffet for 25,-. ');
insert into white_card (text) values ('Domino\'s Oreo(TM) Dessert Pizza. ');
insert into white_card (text) values ('Kanye West. ');
insert into white_card (text) values ('Varm ost. ');
insert into white_card (text) values ('Raptorangreb. ');
insert into white_card (text) values ('Topstripning. ');
insert into white_card (text) values ('Nakkeost. ');
insert into white_card (text) values ('Alkoholisme. ');
insert into white_card (text) values ('En midaldrende mand på rulleskøjter. ');
insert into white_card (text) values ('Care Bear-blikket. ');
insert into white_card (text) values ('Bolimi. ');
insert into white_card (text) values ('Overstore slikkepinde. ');
insert into white_card (text) values ('Selvhad. ');
insert into white_card (text) values ('Børn i snor. ');
insert into white_card (text) values ('Halvringe forspil. ');
insert into white_card (text) values ('Den Hellige Bibel. ');
insert into white_card (text) values ('Tysk kælderporno. ');
insert into white_card (text) values ('At brænde. ');
insert into white_card (text) values ('Gravide teenagere. ');
insert into white_card (text) values ('Gandhi. ');
insert into white_card (text) values ('En akavet voicemail. ');
insert into white_card (text) values ('Uppercuts. ');
insert into white_card (text) values ('Supportfolk. ');
insert into white_card (text) values ('En stivert der holder længere end fire timer. ');
insert into white_card (text) values ('Mine genitalier. ');
insert into white_card (text) values ('At score tøser på abortklinikken. ');
insert into white_card (text) values ('Videnskab. ');
insert into white_card (text) values ('Ikke at reagere på oralsex. ');
insert into white_card (text) values ('Fugle der ikke kan flyve. ');
insert into white_card (text) values ('Et godt snif. ');
insert into white_card (text) values ('Vandtortur. ');
insert into white_card (text) values ('Et velbalanceret  morgenmåltid. ');
insert into white_card (text) values ('Tosprogede skoler.  ');
insert into white_card (text) values ('At rent faktisk stjæle slik fra et barn. ');
insert into white_card (text) values ('Ønskefonden.  ');
insert into white_card (text) values ('En næsten  umærkelig røvkløen. ');
insert into white_card (text) values ('Passivt-aggresive  Post-it sedler.  ');
insert into white_card (text) values ('Det kinesiske gymnastikhold. ');
insert into white_card (text) values ('At skifte til Alka. ');
insert into white_card (text) values ('At tisse en lille smule. ');
insert into white_card (text) values ('Våde drømme. ');
insert into white_card (text) values ('Jøderne. ');
insert into white_card (text) values ('Mine buler. ');
insert into white_card (text) values ('Stærke lår. ');
insert into white_card (text) values ('At blinke til ældre mennesker. ');
insert into white_card (text) values ('Mr. Clean, lige bag dig. ');
insert into white_card (text) values ('Et blidt nus på inderlåret. ');
insert into white_card (text) values ('Sexuelt pres. ');
insert into white_card (text) values ('Den forbudte frugt. ');
insert into white_card (text) values ('Skeletor. ');
insert into white_card (text) values ('Whiskas®. ');
insert into white_card (text) values ('Rigdom. ');
insert into white_card (text) values ('Skøn, skøn hævn. ');
insert into white_card (text) values ('Republikanere. ');
insert into white_card (text) values ('En gassende antelope. ');
insert into white_card (text) values ('Natalie Portman. ');
insert into white_card (text) values ('Gramsning. ');
insert into white_card (text) values ('Selvmords-piloter. ');
insert into white_card (text) values ('Sean Connery. ');
insert into white_card (text) values ('Den homoseksuelle dagsorden. ');
insert into white_card (text) values ('Den hårdtarbejdende Polak. ');
insert into white_card (text) values ('En falk med en kalot på hovedet. ');
insert into white_card (text) values ('Alterdrenge. ');
insert into white_card (text) values ('At blive så sur at du får stivert. ');
insert into white_card (text) values ('Gratis prøver. ');
insert into white_card (text) values ('En storm i et glas vand. ');
insert into white_card (text) values ('At gøre det rigtige. ');
insert into white_card (text) values ('Systemskiftet. ');
insert into white_card (text) values ('Brystmælk. ');
insert into white_card (text) values ('Verdensfreden. ');
insert into white_card (text) values ('RoboCop. ');
insert into white_card (text) values ('Mod. ');
insert into white_card (text) values ('Justin Bieber. ');
insert into white_card (text) values ('Smølfer. ');
insert into white_card (text) values ('Upassende jodlen. ');
insert into white_card (text) values ('Pubertet. ');
insert into white_card (text) values ('Spøgelser. ');
insert into white_card (text) values ('Et asymmetrisk boobjob. ');
insert into white_card (text) values ('Energifulde jazzhænder. ');
insert into white_card (text) values ('Finger. ');
insert into white_card (text) values ('Sidney Lee med skrotum spiddet på et hegn. ');
insert into white_card (text) values ('Yoggi. ');
insert into white_card (text) values ('Politivold. ');
insert into white_card (text) values ('Struensee. ');
insert into white_card (text) values ('10-årige. ');
insert into white_card (text) values ('Skalpering. ');
insert into white_card (text) values ('At "Tweete”. ');
insert into white_card (text) values ('Darth Vader. ');
insert into white_card (text) values ('Et sørgeligt handjob. ');
insert into white_card (text) values ('Præcis hvad du ville forvente. ');
insert into white_card (text) values ('At forvente en bøvs og så brække sig på gulvet. ');
insert into white_card (text) values ('Hjernedoping. ');
insert into white_card (text) values ('Stamceller. ');
insert into white_card (text) values ('Smagfuld sidebabs. ');
insert into white_card (text) values ('Pandasex. ');
insert into white_card (text) values ('At få lavet hul i hovedet med en isøkse. ');
insert into white_card (text) values ('Tom Cruise. ');
insert into white_card (text) values ('Mundherpes. ');
insert into white_card (text) values ('Kaskelothvaler. ');
insert into white_card (text) values ('Hjemløse. ');
insert into white_card (text) values ('Den første gang. ');
insert into white_card (text) values ('Incest. ');
insert into white_card (text) values ('Pac-Man der ukontrollabelt sluprer sæd. ');
insert into white_card (text) values ('En mimer der får en hjerneblødning. ');
insert into white_card (text) values ('Biker Jens. ');
insert into white_card (text) values ('Gud. ');
insert into white_card (text) values ('Skrubning under folderne. ');
insert into white_card (text) values ('Golden Shower ');
insert into white_card (text) values ('Følelser. ');
insert into white_card (text) values ('At slikke ting for at erklære dem din ejendom. ');
insert into white_card (text) values ('Thy Pilsner. ');
insert into white_card (text) values ('Moderkagen. ');
insert into white_card (text) values ('Mennesker der pludselig eksploderer. ');
insert into white_card (text) values ('Bollevenner. ');
insert into white_card (text) values ('Fingermaling. ');
insert into white_card (text) values ('Lugten af gammel dame. ');
insert into white_card (text) values ('At dø af dysenteri/tyndskid. ');
insert into white_card (text) values ('Mine indre dæmoner. ');
insert into white_card (text) values ('Et vandgevær fyldt med kattetis. ');
insert into white_card (text) values ('Amin Jensen. ');
insert into white_card (text) values ('Nusning. ');
insert into white_card (text) values ('Det kroniske. ');
insert into white_card (text) values ('Hanekampe. ');
insert into white_card (text) values ('Vådeskud. ');
insert into white_card (text) values ('Ronald Reagan. ');
insert into white_card (text) values ('En skuffende fødselsdagsfest. ');
insert into white_card (text) values ('En selvglad sort kvinde. ');
insert into white_card (text) values ('Matleter. ');
insert into white_card (text) values ('En lillebitte hest. ');
insert into white_card (text) values ('Anders Matthesen. ');
insert into white_card (text) values ('At ride ud i solnedgangen. ');
insert into white_card (text) values ('Et plot twist af M. Night Shyamalan. ');
insert into white_card (text) values ('Jøder med afrohår. ');
insert into white_card (text) values ('Udslettelse på begge sider. ');
insert into white_card (text) values ('Pædofile. ');
insert into white_card (text) values ('Svamp. ');
insert into white_card (text) values ('Gravrøveri. ');
insert into white_card (text) values ('At spise den sidste bison. ');
insert into white_card (text) values ('Katapulter.  ');
insert into white_card (text) values ('Fattige folk. ');
insert into white_card (text) values ('At glemme den 11. september. ');
insert into white_card (text) values ('Stress. ');
insert into white_card (text) values ('The Force. ');
insert into white_card (text) values ('At tørre hendes bag.  ');
insert into white_card (text) values ('Intelligent design. ');
insert into white_card (text) values ('Løse læber. ');
insert into white_card (text) values ('AIDS. ');
insert into white_card (text) values ('Billeder af bryster. ');
insert into white_card (text) values ('Übermensch. ');
insert into white_card (text) values ('Sarah Palin. ');
insert into white_card (text) values ('Amerikanske gladiatorer. ');
insert into white_card (text) values ('At ryge sig virkelig høj. ');
insert into white_card (text) values ('Scientology. ');
insert into white_card (text) values ('Penis-misundelighed. ');
insert into white_card (text) values ('At bede til Gud indtil bøssen forsvinder. ');
insert into white_card (text) values ('At hygge sig. ');
insert into white_card (text) values ('To dværge der skider i en spand. ');
insert into white_card (text) values ('Ku Klux Klan. ');
insert into white_card (text) values ('Genghis Khan. ');
insert into white_card (text) values ('Amfetamin. ');
insert into white_card (text) values ('Stavnsbåndet. ');
insert into white_card (text) values ('Farlige fremmede. ');
insert into white_card (text) values ('Flaskehalsen peger på. ');
insert into white_card (text) values ('Amalies skuespilkarriere. ');
insert into white_card (text) values ('Frøhop. ');
insert into white_card (text) values ('Selvtægt. ');
insert into white_card (text) values ('Overkompensation. ');
insert into white_card (text) values ('Pixelleret bukkake. ');
insert into white_card (text) values ('Et sørgeligt liv. ');
insert into white_card (text) values ('Racisme. ');
insert into white_card (text) values ('Dværgekast. ');
insert into white_card (text) values ('Solskin og regnbuer. ');
insert into white_card (text) values ('En abe der ryger en cigar. ');
insert into white_card (text) values ('Lynoversvømmelser. ');
insert into white_card (text) values ('Lance Armstrongs manglende testikel. ');
insert into white_card (text) values ('Hævning. ');
insert into white_card (text) values ('Terroristerne. ');
insert into white_card (text) values ('Britney Spears som 55-årig. ');
insert into white_card (text) values ('Attitude. ');
insert into white_card (text) values ('Pludselig sang og dans. ');
insert into white_card (text) values ('Spedalskhed. ');
insert into white_card (text) values ('Glory Holes. ');
insert into white_card (text) values ('Patteklinger. ');
insert into white_card (text) values ('Et barns hjerte. ');
insert into white_card (text) values ('Hvalpe! ');
insert into white_card (text) values ('At vågne halvnøgen på parkeringspladsen udenfor en Bone\'s. ');
insert into white_card (text) values ('Kanintænder. ');
insert into white_card (text) values ('Ghita Nørbys vagina. ');
insert into white_card (text) values ('Stedet mellem benene. ');
insert into white_card (text) values ('Aktiv lytning. ');
insert into white_card (text) values ('Etnisk udrensning. ');
insert into white_card (text) values ('Toget Thomas. ');
insert into white_card (text) values ('Den usynlige hånd. ');
insert into white_card (text) values ('Afholdenhed indtil brylluppet. ');
insert into white_card (text) values ('Ufattelig dumhed. ');
insert into white_card (text) values ('Euphoria af Calvin Klein. ');
insert into white_card (text) values ('Gaveompakning. ');
insert into white_card (text) values ('Autokannibalisme. ');
insert into white_card (text) values ('Impotens. ');
insert into white_card (text) values ('Min samling af højteknologisk sexlegetøj. ');
insert into white_card (text) values ('Paven. ');
insert into white_card (text) values ('Hvide mennesker. ');
insert into white_card (text) values ('Tentakelporno. ');
insert into white_card (text) values ('Sidney Lee der kaster voldsomt op mens et bundt krabbeedderkopper klækker ud inde i hans hjerne og kravler ud af hans tårekanaler. ');
insert into white_card (text) values ('For meget hårvoks. ');
insert into white_card (text) values ('Seppuku. (Harakiri) ');
insert into white_card (text) values ('Kunstskøjtning med samme køn. ');
insert into white_card (text) values ('Snyd i handicap-olympiaden. ');
insert into white_card (text) values ('Karisma. ');
insert into white_card (text) values ('Keanu Reeves. ');
insert into white_card (text) values ('Niels Olsen. ');
insert into white_card (text) values ('Nickelback. ');
insert into white_card (text) values ('En kigger. ');
insert into white_card (text) values ('At skide frem og tilbage - for evigt. ');
insert into white_card (text) values ('Menstruation. ');
insert into white_card (text) values ('Børn med røvkræft. ');
insert into white_card (text) values ('En saltet overraskelse. ');
insert into white_card (text) values ('Syden. ');
insert into white_card (text) values ('Bruddet på vores mest grundlæggende menneske-rettigheder ');
insert into white_card (text) values ('Voldtægt på daten. ');
insert into white_card (text) values ('At være skøn. ');
insert into white_card (text) values ('Nekrofili. ');
insert into white_card (text) values ('Kentaurer. ');
insert into white_card (text) values ('Store Nørd. ');
insert into white_card (text) values ('Sorte folk. ');
insert into white_card (text) values ('Ærlighed. ');
insert into white_card (text) values ('Fabriksmad. ');
insert into white_card (text) values ('Kællinger. ');
insert into white_card (text) values ('De virkeligt handicappede. ');
insert into white_card (text) values ('Hjertevarmende forældreløse børn. ');
insert into white_card (text) values ('MechaHitler. ');
insert into white_card (text) values ('Brændende skideture. ');
insert into white_card (text) values ('Endnu en forbandet vampyrfilm. ');
insert into white_card (text) values ('Sammenkrøllede hoppefjedre. ');
insert into white_card (text) values ('Julens virkelige mening. ');
insert into white_card (text) values ('Østrogen. ');
insert into white_card (text) values ('En klam frokostpizza. ');
insert into white_card (text) values ('Den der ting der giver stød til din mave. ');
insert into white_card (text) values ('Videresending af en gallesten. ');
insert into white_card (text) values ('Et afbleget røvhul. ');
insert into white_card (text) values ('Michael Jackson. ');
insert into white_card (text) values ('Robot-implantater. ');
insert into white_card (text) values ('Fyre der ikke ringer. ');
insert into white_card (text) values ('Tæpper med kopper ');
insert into white_card (text) values ('Onani. ');
insert into white_card (text) values ('Klassiske undertoner. ');
insert into white_card (text) values ('Fisseprutter. ');
insert into white_card (text) values ('At skjule en stivert. ');
insert into white_card (text) values ('Spiselige underbukser. ');
insert into white_card (text) values ('Viagra®. ');
insert into white_card (text) values ('Suppe der er for varm. ');
insert into white_card (text) values ('Muhammed (Æret Være Han). ');
insert into white_card (text) values ('Surprise sex! ');
insert into white_card (text) values ('Sandwich for en tyver. ');
insert into white_card (text) values ('Enedruk. ');
insert into white_card (text) values ('Pikfingre. ');
insert into white_card (text) values ('Adskillige stiksår. ');
insert into white_card (text) values ('At skide i bukserne. ');
insert into white_card (text) values ('Børnemishandling. ');
insert into white_card (text) values ('Analperler. ');
insert into white_card (text) values ('Civile tab. ');
insert into white_card (text) values ('At trække ud. ');
insert into white_card (text) values ('Robert Downey, Jr. ');
insert into white_card (text) values ('Hestekød. ');
insert into white_card (text) values ('En virkelig sej hat. ');
insert into white_card (text) values ('Kim Jong-il. ');
insert into white_card (text) values ('Et kønshår. ');
insert into white_card (text) values ('Jødeloger. ');
insert into white_card (text) values ('Den ubetydelige minoritet. ');
insert into white_card (text) values ('At gøre det i nummi\'. ');
insert into white_card (text) values ('Fodring af Merethe. ');
insert into white_card (text) values ('At lære en robot at elske. ');
insert into white_card (text) values ('En dåse whoop-ass. ');
insert into white_card (text) values ('En mølle fyldt med lig. ');
insert into white_card (text) values ('Coco Pops. ');
insert into white_card (text) values ('Omvendt undertøj for at undgå at skulle vaske. ');
insert into white_card (text) values ('En dødsstråle. ');
insert into white_card (text) values ('Glasloftet. ');
insert into white_card (text) values ('Et køleskab fyldt med organer. ');
insert into white_card (text) values ('Den Amerikanske Drøm. ');
insert into white_card (text) values ('Ølfad. ');
insert into white_card (text) values ('Når du prutter og en lille smule kommer ud. ');
insert into white_card (text) values ('Hævnaktioner. ');
insert into white_card (text) values ('Døde babyer. ');
insert into white_card (text) values ('Forhud. ');
insert into white_card (text) values ('Saxofonsoloer. ');
insert into white_card (text) values ('Italienere. ');
insert into white_card (text) values ('Et foster. ');
insert into white_card (text) values ('At skyde et gevær op i luften mens man er i til roden i en pibende gris. ');
insert into white_card (text) values ('Lars Løkke Rasmussen. ');
insert into white_card (text) values ('Amputerede. ');
insert into white_card (text) values ('Eugenik. ');
insert into white_card (text) values ('Min forholdsstatus. ');
insert into white_card (text) values ('Christopher Walken. ');
insert into white_card (text) values ('Bier? ');
insert into white_card (text) values ('Harry Potter porno. ');
insert into white_card (text) values ('Gymnasiet. ');
insert into white_card (text) values ('At blive beruset af mundskyl. ');
insert into white_card (text) values ('Nazier. ');
insert into white_card (text) values ('Et halvt kilo heroin. ');
insert into white_card (text) values ('Dirty talk af Stephen Hawking. ');
insert into white_card (text) values ('Døde forældre. ');
insert into white_card (text) values ('Objektpermanens. ');
insert into white_card (text) values ('Omvendte tommelfingre. ');
insert into white_card (text) values ('Racistiske eksamensopgaver. ');
insert into white_card (text) values ('Sludder for en sladder.  ');
insert into white_card (text) values ('Motorsave i stedet for hænder. ');
insert into white_card (text) values ('Nicolas Cage. ');
insert into white_card (text) values ('Børnemodeller. ');
insert into white_card (text) values ('Eksplosioner.  ');
insert into white_card (text) values ('Limsnifning.  ');
insert into white_card (text) values ('Sidney Lee der bliver angrebet af en flok gribbe. ');
insert into white_card (text) values ('Undertrykkelse. ');
insert into white_card (text) values ('Sovemedicin. ');
insert into white_card (text) values ('Min kusse. ');
insert into white_card (text) values ('Fyre uden røve. ');
insert into white_card (text) values ('Et grimt stygt mord. ');
insert into white_card (text) values ('At give 110%. ');
insert into white_card (text) values ('Hendes Kongelige Majestæt, Dronning Magrethe d. 2. ');
insert into white_card (text) values ('Sporet af tårer. ');
insert into white_card (text) values ('Tilsidesætning. ');
insert into white_card (text) values ('Gobliner. ');
insert into white_card (text) values ('Håb. ');
insert into white_card (text) values ('Martin Luther King. ');
insert into white_card (text) values ('En mikropenis. ');
insert into white_card (text) values ('Min sjæl. ');
insert into white_card (text) values ('Et varmt griseri.  ');
insert into white_card (text) values ('Vikinger.  ');
insert into white_card (text) values ('Hotte mennesker. ');
insert into white_card (text) values ('Tilnærmelser.  ');
insert into white_card (text) values ('Et Ødipuskompleks. ');
insert into white_card (text) values ('Gæs. ');
insert into white_card (text) values ('Global opvarmning. ');
insert into white_card (text) values ('New Age musik.  ');
insert into white_card (text) values ('Oppustning.  ');
insert into white_card (text) values ('Vejdrab. ');
insert into white_card (text) values ('Kvinders stemmeret. ');
insert into white_card (text) values ('Et defekt kondom. ');
insert into white_card (text) values ('En højesteretsdommer. ');
insert into white_card (text) values ('Afrikanske børn. ');
insert into white_card (text) values ('En skolemassakre. ');
insert into white_card (text) values ('Barack Obama. ');
insert into white_card (text) values ('Asiatere der ikke er gode til matematik. ');
insert into white_card (text) values ('Gamle japanske mænd. ');
insert into white_card (text) values ('En venlig samtale. ');
insert into white_card (text) values ('Kønsroller. ');
insert into white_card (text) values ('Åbning af det røde hav. ');
insert into white_card (text) values ('Arnold Schwarzenegger ');
insert into white_card (text) values ('Et blowjob i bilen. ');
insert into white_card (text) values ('Spektakulære mavemuskler. ');
insert into white_card (text) values ('Krummet budding. ');
insert into white_card (text) values ('En gnaven løve i zoo. ');
insert into white_card (text) values ('Vingummibamser. ');
insert into white_card (text) values ('Dårlige valg i livet. ');
insert into white_card (text) values ('Mit sexliv. ');
insert into white_card (text) values ('Auschwitz. ');
insert into white_card (text) values ('En skildpadde der bider spidsen af din diller. ');
insert into white_card (text) values ('En brintbombe- eksplosion. ');
insert into white_card (text) values ('Klitorissen. ');
insert into white_card (text) values ('Big Bang. ');
insert into white_card (text) values ('Landminer. ');
insert into white_card (text) values ('Venner som æder alle snacks\'ne. ');
insert into white_card (text) values ('Geder der spiser dåsen ');
insert into white_card (text) values ('Tandfeens dans. ');
insert into white_card (text) values ('At rive den af i et kar fyldt med babytårer. ');
insert into white_card (text) values ('Mandekød. ');
insert into white_card (text) values ('Tid til mig selv. ');
insert into white_card (text) values ('Den Underjordiske Jernbane. ');
insert into white_card (text) values ('Dårligt timede Holocaust-jokes. ');
insert into white_card (text) values ('Et hav af problemer. ');
insert into white_card (text) values ('Fantasier om skovhuggere. ');
insert into white_card (text) values ('Morgan Freeman\'s stemme. ');
insert into white_card (text) values ('Kvinder i yoghurt- reklamer. ');
insert into white_card (text) values ('Naturlig manddoms-forlængelse. ');
insert into white_card (text) values ('At være en motherfucking troldmand. ');
insert into white_card (text) values ('Kønspiercinger. ');
insert into white_card (text) values ('Umistænkelige transvetitter. ');
insert into white_card (text) values ('Sexede pudekampe. ');
insert into white_card (text) values ('Kugler. ');
insert into white_card (text) values ('Bedstemor. ');
insert into white_card (text) values ('Friktion. ');
insert into white_card (text) values ('Lyseslukkere. ');
insert into white_card (text) values ('At hørme og gå væk. ');
insert into white_card (text) values ('At være et røvhul overfor børn. ');
insert into white_card (text) values ('At fylde huset med bomber for at dræbe indbrudstyve. ');
insert into white_card (text) values ('En vandseng fyldt med vaseline. ');
insert into white_card (text) values ('Død. ');
insert into white_card (text) values ('Orkanen Katrina. ');
insert into white_card (text) values ('Bøsserne. ');
insert into white_card (text) values ('Menneskehedens fejl. ');
insert into white_card (text) values ('Mænd ');
insert into white_card (text) values ('The Amish. ');
insert into white_card (text) values ('Pterodactyl-æg. ');
insert into white_card (text) values ('Teamworksøvelser. ');
insert into white_card (text) values ('En hjernetumor. ');
insert into white_card (text) values ('Frygten selv. ');
insert into white_card (text) values ('Lady Gaga. ');
insert into white_card (text) values ('Mælkemanden. ');
insert into white_card (text) values ('En fæl mund. ');
insert into white_card (text) values ('Cards Against Humanity ');
