insert into black_card (text) values ('Hvad er Batmans "guilty pleasure"? ');
insert into black_card (text) values ('Hvad er min hemmelige superkraft? ');
insert into black_card (text) values ('Hvordan vedligeholder jeg min forholdsstatus? ');
insert into black_card (text) values ('Hvad er mit antistof? ');
insert into black_card (text) values ('Hvad er den nye modemad? ');
insert into black_card (text) values ('Hvad er det sprødeste? ');
insert into black_card (text) values ('Hvad tog jeg med tilbage fra Tyskland? ');
insert into black_card (text) values ('Hvad spiste Vin Diesel til aftensmad? ');
insert into black_card (text) values ('Hvad vil jeg tage med tilbage i tiden for at få folk til at tro jeg er en magtfuld magiker? ');
insert into black_card (text) values ('Hvad bliver bedre med tiden? ');
insert into black_card (text) values ('Hvad bruger skolelærere i de store byer nu for at få eleverne til at klare sig godt? ');
insert into black_card (text) values ('Hvorfor har jeg ondt over det hele? ');
insert into black_card (text) values ('Hvad skjuler mine forældre fra mig? ');
insert into black_card (text) values ('Hvad er en piges bedste ven? ');
insert into black_card (text) values ('Hvad gør altid en fest mere livlig? ');
insert into black_card (text) values ('Hvad gjorde en ende på mit sidste forhold? ');
insert into black_card (text) values ('Hvad bliver det næste Happy Meal® legetøj? ');
insert into black_card (text) values ('Hvad ville bedstemor finde bekymrende, men mærkeligt charmerende? ');
insert into black_card (text) values ('Hvad er det for en lyd? ');
insert into black_card (text) values ('Hvad er der et ton af i himlen? ');
insert into black_card (text) values ('Hvorfor kan jeg ikke sove om natten? ');
insert into black_card (text) values ('Hvad er mest emo? ');
insert into black_card (text) values ('Det er sådan jeg vil dø. ');
insert into black_card (text) values ('Hvad er det for en lugt? ');
insert into black_card (text) values ('Hvorfor er jeg klistret? ');
insert into black_card (text) values ('Hvad vil altid ende med at du får noget på den dumme? ');
insert into black_card (text) values ('Hvad hjælper Obama med at afstresse? ');
insert into black_card (text, cards_to_pick) values ('Hvad er det næste Superhelte-makkerpar? ', 2);
insert into black_card (text) values ('Krig! Hvad nytte er det til? ');
insert into black_card (text) values ('Hvad har du ikke lyst til at finde i din kinesermad? ');
insert into black_card (text) values ('Hvad giver mig ukontrollerbar luft i maven?');
insert into black_card (text) values ('Hvad smed USA ned i faldskærm til børnene i Afghanistan?');
insert into black_card (text) values ('Hvad lugter gamle mennesker af?');
insert into black_card (text) values ('Hvad foretrækker Lars Løkke Rasmussen?');
insert into black_card (text) values ('Hvad opgiver jeg i Fasten? ');
insert into black_card (text, cards_to_pick, cards_to_draw) values ('Lav et haiku.',3,2);
insert into black_card (text) values ('Luftfartsmyndighederne forbyder nu __ på rutefly. ');
insert into black_card (text) values ('__. Du kan ikke nøjes med bare en!');
insert into black_card (text) values ('Det er en skam at børn nu til dags alle sammen bliver involverede i __');
insert into black_card (text) values ('Jeg er ked af det, professor, men jeg kunne ikke lave mine lektier på grund af __');
insert into black_card (text) values ('Om 1.000 år, når papirpenge blot er et fjernt minde, vil __ være vores valuta. ');
insert into black_card (text) values ('Mens USA og Sovjet-unionen havde kapløb om at komme til månen, brugte den mexicanske regering millioner af peso på forskning i __ ');
insert into black_card (text) values ('Rygtet siger at du kan bytte 200 cigaretter for __ i Horsens Statsfængsel.');
insert into black_card (text) values ('Dansk Bold Union har forbudt __,  fordi det giver en unfair fordel. ');
insert into black_card (text) values ('__ ? Det er der en app til. ');
insert into black_card (text) values ('I den nye Original-film på Disney Channel, kæmper Hannah Montana med ___ for første gang. ');
insert into black_card (text) values ('Da faraoen forblev urokkeiig, kaldte på Moses på en plage af __ ');
insert into black_card (text) values ('Efter Jordskælvet bragte Jonathan Spang __ til Haitis folk. ');
insert into black_card (text) values ('I stedet for kul giver Julemanden nu de slemme børn  __ ');
insert into black_card (text) values ('I Michael Jacksons sidste øjeblikke tænkte han på __ ');
insert into black_card (text) values ('Kære Trine, jeg har problemer med __ og vil gerne høre dine råd. ');
insert into black_card (text) values ('Indianernes Iiv blev for evigt forandret da de hvide gav dem __ ');
insert into black_card (text) values ('Hvide mennesker kan lide __ ');
insert into black_card (text) values ('Billy Mays here for __');
insert into black_card (text) values ('Når jeg bliver statsminister vil jeg oprette Ministeriet for __ ');
insert into black_card (text) values ('__ Godt til sidste dråbe.');
insert into black_card (text) values ('Klasseturen blev fuldstændig ødelagt af __ ');
insert into black_card (text) values ('Jeg har 99 problemer, men __ er ikke et. ');
insert into black_card (text) values ('Måske er hun født med det. Måske er det __ ');
insert into black_card (text) values ('En romantisk, stearinoplyst middag ville ikke være komplet uden __ ');
insert into black_card (text) values ('__ Det er en fælde! ');
insert into black_card (text) values ('MTV\'s nye realityshow handler om otte tidligere kendte der lever med __ ');
insert into black_card (text) values ('__ Testet af børn, godkendt af mødre. ');
insert into black_card (text) values ('Denne sæson på det Kongelige Teater, __ The Musical. ');
insert into black_card (text) values ('Antropologer har for nyligt opdaget en primitiv stamme der tilbeder __');
insert into black_card (text) values ('Jeg ved ikke hvilke våben Tredje Verdenskrig vil blive udkæmpet med, men Fjerde Verdenskrig vil blive udkæmpet med __');
insert into black_card (text) values ('Men før jeg dræber dig, Mr. Bond, skal jeg vise dig __');
insert into black_card (text) values ('Mens jeg har sex, kan jeg lide at tænke på __');
insert into black_card (text) values ('Undersøgelser viser at rotter finder vej igennem labyrinter 50% hurtigere efter at have været udsat for __');
insert into black_card (text) values ('Alternativ medicin viser nu interesse i de helbredende krafter i __');
insert into black_card (text) values ('Snart på Eurosport: VM i __');
insert into black_card (text) values ('Jeg drikker for at glemme __');
insert into black_card (text) values ('Når jeg er milliardær, vil jeg bygge en 15 meter høj statue til minde om __');
insert into black_card (text) values ('__ High five, kammerat.');
insert into black_card (text) values ('I et forsøg på at nå en bredere folkemængde, har Naturhistorisk Museum åbnet en interaktiv udstilling om __');
insert into black_card (text) values ('Under Picassos ofte oversete "Brune Periode" producerede han hundredevis af billeder af  __');
insert into black_card (text, cards_to_pick) values ('Da jeg var på syre, blev __ til  __ ', 2);
insert into black_card (text, cards_to_pick) values ('Og Oscaren for __ går til __ ', 2);
insert into black_card (text, cards_to_pick) values ('Som mit næste trick, vil jeg hive __ op af  __ ', 2);
insert into black_card (text, cards_to_pick) values ('Trin 1: __ Trin 2: __ Trin 3: Profit. ', 2);
insert into black_card (text, cards_to_pick) values ('Det er rigtigt, jeg dræbte __ Hvordan, spørger du? __ ', 2);
insert into black_card (text, cards_to_pick) values ('__ er en glidebane der fører til __ ', 2);
insert into black_card (text, cards_to_pick) values ('Rygtet siger, at Vladimir Putins yndlingsret er __ stoppet med __ ', 2);
insert into black_card (text, cards_to_pick) values ('I en verden ødelagt af  __ er __ vores eneste redning. ', 2);
insert into black_card (text, cards_to_pick) values ('Kanal 5 præsenterer __ historien om __ ', 2);
insert into black_card (text, cards_to_pick) values ('I M. Night Shyamalans nye film opdager Bruce Willis at __ i virkeligheden var __ hele tiden. ', 2);
insert into black_card (text, cards_to_pick) values ('Jeg forstod aldrig helt __ indtil jeg mødte  __ ', 2);
insert into black_card (text, cards_to_pick, cards_to_draw) values ('__ + __ = __', 3, 2);
