insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__?  There's an app for that.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Why can't I sleep at night?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's that smell?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("I got 99 problems but __ ain't one.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Maybe she's born with it.  Maybe it's __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's the next Happy Meal (C) toy?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Anthropologists have recently discovered a primitive tribe that worships __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("It's a pity that kids these days are all getting involved with __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Alternative medicine is now embracing the curative powers of __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("And the Academy Award for __ goes to __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's that sound?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What ended my last relationship?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("MTV's new reality show features eight washed-up celebrities living with __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("I drink to forget __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("I'm sorry professor, but I couldn't complete my homework because of __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What is Batman's guilty pleasure?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("This is the way the world ends <br> This is the way the world ends <br> Not with a bang but with __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's a girl's best friend?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("TSA guidelines now prohibit __ on airplanes.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__.  That's how I want to die.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("For my next trick, I will pull __ out of __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("In the new Disney Channel Original Movie, Hannah Montana struggles with __ for the first time.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__ is a slippery slope that leads to __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What does Dick Cheney prefer?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Dear Abby, I'm having some trouble with __ and would like your advice.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Instead of coal, Santa now gives the bad children __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's the most emo?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("In 1,000 years when paper money is but a distant memory, __ will be our currency.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's the next superhero/sidekick duo?",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("In M. Night Shyamalan's new movie, Bruce Willis discovers that __ had really been __ all along.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("A romantic, candlelit dinner would be incomplete without __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__.  Becha can't have just one!",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("White people like __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__.  High five, bro.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Next from J.K. Rowling: Harry Potter and the Chamber of __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("BILLY MAYS HERE FOR __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("In a world ravaged by __, our only solace is __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("War!  What is it good for?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("During sex, I like to think about __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What are my parents hiding from me?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What will always get you laid?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("In L.A. County Jail, word is you can trade 200 cigarettes for __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What did I bring back from Mexico?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What don't you want to find in your Chinese food?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What will I bring back in time to convince people that I am a powerful wizard?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("How am I maintaining my relationship status?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__.  It's a trap!",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Coming to Broadway this season, __: The Musical.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("After the earthquake, Sean Penn brought __ to the people of Haiti.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Next on ESPN2, the World Series of __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Step 1: __.  Step 2: __.  Step 3: Profit.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Rumor has it that Vladimir Putin's favorite dish is __ stuffed with __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("But before I kill you, Mr. Bond, I must show you __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What gives me uncontrollable gas?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What do old people smell like?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("The class field trip was completely ruined by __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("When Pharaoh remained unmoved, Moses called down a Plague of __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's my secret power?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's there a ton of in heaven?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What would grandma find disturbing, yet oddly charming?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("I never truly understood __ until I encountered __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What did the U.S. airdrop to the children of Afghanistan?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What helps Obama unwind?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What did Vin Diesel eat for dinner?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__: good to the last drop.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Why am I sticky?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What gets better with age?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__: kid-tested, mother-approved.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's the crustiest?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's Teach for America using to inspire inner city students to succeed?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Studies show that lab rats navigate mazes 50% faster after being exposed to __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Life for American Indians was forever changed when the White Man introduced them to __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Make a haiku.",3,2, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("I do not know with what weapons World War III will be fought, but World War IV will be fought with __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Why do I hurt all over?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What am I giving up for Lent?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("In Michael Jackson's final moments, he thought about __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("When I am President of the United States, I will create the Department of __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Lifetime (C) presents __, the story of __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("When I am a billionaire, I shall erect a 50-foot statue to commemorate __.",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("When I was tripping on acid, __ turned into __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("That's right, I killed __.  How, you ask?  __.",2,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's my anti-drug?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("__ + __ = __.",3,2, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What never fails to liven up the party?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("What's the new fad diet?",1,0, 2);
insert into black_card (text,cards_to_pick,cards_to_draw,deck_id) values ("Major League Baseball has banned __ for giving players an unfair advantage.",1,0, 2);
