insert into white_card (text,deck_id) values ("Flying sex snakes.", 2);
insert into white_card (text,deck_id) values ("Michelle Obama's arms.", 2);
insert into white_card (text,deck_id) values ("German dungeon porn.", 2);
insert into white_card (text,deck_id) values ("White people.", 2);
insert into white_card (text,deck_id) values ("Getting so angry that you pop a boner.", 2);
insert into white_card (text,deck_id) values ("Tasteful sideboob.", 2);
insert into white_card (text,deck_id) values ("Praying the gay away.", 2);
insert into white_card (text,deck_id) values ("Two midgets shitting into a bucket.", 2);
insert into white_card (text,deck_id) values ("MechaHitler.", 2);
insert into white_card (text,deck_id) values ("Being a motherfucking sorcerer.", 2);
insert into white_card (text,deck_id) values ("A disappointing birthday party.", 2);
insert into white_card (text,deck_id) values ("Puppies!", 2);
insert into white_card (text,deck_id) values ("A windmill full of corpses.", 2);
insert into white_card (text,deck_id) values ("Guys who don't call.", 2);
insert into white_card (text,deck_id) values ("Racially-biased SAT questions.", 2);
insert into white_card (text,deck_id) values ("Dying.", 2);
insert into white_card (text,deck_id) values ("Steven Hawking talking dirty.", 2);
insert into white_card (text,deck_id) values ("Being on fire.", 2);
insert into white_card (text,deck_id) values ("A lifetime of sadness.", 2);
insert into white_card (text,deck_id) values ("An erection that lasts longer than four hours.", 2);
insert into white_card (text,deck_id) values ("AIDS", 2);
insert into white_card (text,deck_id) values ("Same-sex ice dancing.", 2);
insert into white_card (text,deck_id) values ("Glenn Beck catching his scrotum on a curtain hook.", 2);
insert into white_card (text,deck_id) values ("The Rapture.", 2);
insert into white_card (text,deck_id) values ("Pterodactyl eggs.", 2);
insert into white_card (text,deck_id) values ("Crippling debt.", 2);
insert into white_card (text,deck_id) values ("Eugenics.", 2);
insert into white_card (text,deck_id) values ("Exchanging pleasantries.", 2);
insert into white_card (text,deck_id) values ("Dying of dysentery.", 2);
insert into white_card (text,deck_id) values ("Roofies.", 2);
insert into white_card (text,deck_id) values ("Getting naked and watching Nickelodeon.", 2);
insert into white_card (text,deck_id) values ("The forbidden fruit.", 2);
insert into white_card (text,deck_id) values ("Republicans.", 2);
insert into white_card (text,deck_id) values ("The Big Bang.", 2);
insert into white_card (text,deck_id) values ("Anal beads.", 2);
insert into white_card (text,deck_id) values ("Amputees.", 2);
insert into white_card (text,deck_id) values ("Men.", 2);
insert into white_card (text,deck_id) values ("Surprise sex!", 2);
insert into white_card (text,deck_id) values ("Kim Jong-il.", 2);
insert into white_card (text,deck_id) values ("Concealing a boner", 2);
insert into white_card (text,deck_id) values ("Agriculture.", 2);
insert into white_card (text,deck_id) values ("Glenn Beck being harried by a swarm of buzzards.", 2);
insert into white_card (text,deck_id) values ("Making a pouty face.", 2);
insert into white_card (text,deck_id) values ("A salty surprise.", 2);
insert into white_card (text,deck_id) values ("The Jews.", 2);
insert into white_card (text,deck_id) values ("Charisma.", 2);
insert into white_card (text,deck_id) values ("YOU MUST CONSTRUCT ADDITIONAL PYLONS.", 2);
insert into white_card (text,deck_id) values ("Panda sex.", 2);
insert into white_card (text,deck_id) values ("Taking off your shirt.", 2);
insert into white_card (text,deck_id) values ("A drive-by shooting.", 2);
insert into white_card (text,deck_id) values ("Ronald Reagan.", 2);
insert into white_card (text,deck_id) values ("Morgan Freeman's voice.", 2);
insert into white_card (text,deck_id) values ("Breaking out into song and dance.", 2);
insert into white_card (text,deck_id) values ("Jewish fraternities.", 2);
insert into white_card (text,deck_id) values ("Dead babies.", 2);
insert into white_card (text,deck_id) values ("Masturbation.", 2);
insert into white_card (text,deck_id) values ("Hormone injections.", 2);
insert into white_card (text,deck_id) values ("All-you-can-eat shrimp for $4.99.", 2);
insert into white_card (text,deck_id) values ("Incest.", 2);
insert into white_card (text,deck_id) values ("Scalping.", 2);
insert into white_card (text,deck_id) values ("Soup that is too hot.", 2);
insert into white_card (text,deck_id) values ("The &Uuml;bermensch.", 2);
insert into white_card (text,deck_id) values ("Nazis.", 2);
insert into white_card (text,deck_id) values ("Tom Cruise.", 2);
insert into white_card (text,deck_id) values ("Stifling a giggle at the mention of Hutus and Tutsis.", 2);
insert into white_card (text,deck_id) values ("Edible underpants.", 2);
insert into white_card (text,deck_id) values ("The Hustle.", 2);
insert into white_card (text,deck_id) values ("A Super Soaker (TM) full of cat pee.", 2);
insert into white_card (text,deck_id) values ("Figgy pudding.", 2);
insert into white_card (text,deck_id) values ("Object permanence.", 2);
insert into white_card (text,deck_id) values ("Consultants.", 2);
insert into white_card (text,deck_id) values ("Intelligent design.", 2);
insert into white_card (text,deck_id) values ("Nocturnal emissions.", 2);
insert into white_card (text,deck_id) values ("Uppercuts.", 2);
insert into white_card (text,deck_id) values ("Being marginalized.", 2);
insert into white_card (text,deck_id) values ("The profoundly handicapped.", 2);
insert into white_card (text,deck_id) values ("Obesity.", 2);
insert into white_card (text,deck_id) values ("Chutzpah.", 2);
insert into white_card (text,deck_id) values ("Unfathomable stupidity.", 2);
insert into white_card (text,deck_id) values ("Repression.", 2);
insert into white_card (text,deck_id) values ("Attitude.", 2);
insert into white_card (text,deck_id) values ("Passable transvestites.", 2);
insert into white_card (text,deck_id) values ("Party poopers.", 2);
insert into white_card (text,deck_id) values ("The American Dream", 2);
insert into white_card (text,deck_id) values ("Child beauty pageants.", 2);
insert into white_card (text,deck_id) values ("Puberty.", 2);
insert into white_card (text,deck_id) values ("Testicular torsion.", 2);
insert into white_card (text,deck_id) values ("The folly of man.", 2);
insert into white_card (text,deck_id) values ("Nickelback.", 2);
insert into white_card (text,deck_id) values ("Swooping.", 2);
insert into white_card (text,deck_id) values ("Goats eating cans.", 2);
insert into white_card (text,deck_id) values ("The KKK.", 2);
insert into white_card (text,deck_id) values ("Kamikaze pilots.", 2);
insert into white_card (text,deck_id) values ("Horrifying laser hair removal accidents.", 2);
insert into white_card (text,deck_id) values ("Adderall (TM).", 2);
insert into white_card (text,deck_id) values ("A look-see.", 2);
insert into white_card (text,deck_id) values ("Doing the right thing.", 2);
insert into white_card (text,deck_id) values ("The taint; the grundle; the fleshy fun-bridge.", 2);
insert into white_card (text,deck_id) values ("Lactation.", 2);
insert into white_card (text,deck_id) values ("Pabst Blue Ribbon.", 2);
insert into white_card (text,deck_id) values ("Powerful thighs.", 2);
insert into white_card (text,deck_id) values ("Saxophone solos.", 2);
insert into white_card (text,deck_id) values ("The gays.", 2);
insert into white_card (text,deck_id) values ("A middle-aged man on roller skates.", 2);
insert into white_card (text,deck_id) values ("A foul mouth.", 2);
insert into white_card (text,deck_id) values ("The thing that electrocutes your abs.", 2);
insert into white_card (text,deck_id) values ("Heteronormativity.", 2);
insert into white_card (text,deck_id) values ("Cuddling.", 2);
insert into white_card (text,deck_id) values ("Coat hanger abortions.", 2);
insert into white_card (text,deck_id) values ("A big hoopla about nothing.", 2);
insert into white_card (text,deck_id) values ("Boogers.", 2);
insert into white_card (text,deck_id) values ("A hot mess.", 2);
insert into white_card (text,deck_id) values ("Raptor attacks.", 2);
insert into white_card (text,deck_id) values ("My collection of high-tech sex toys.", 2);
insert into white_card (text,deck_id) values ("Fear itself.", 2);
insert into white_card (text,deck_id) values ("<i>Bees?</i>", 2);
insert into white_card (text,deck_id) values ("Getting drunk on mouthwash.", 2);
insert into white_card (text,deck_id) values ("Sniffing glue.", 2);
insert into white_card (text,deck_id) values ("Oversized lollipops.", 2);
insert into white_card (text,deck_id) values ("An icepick lobotomy.", 2);
insert into white_card (text,deck_id) values ("Being rich.", 2);
insert into white_card (text,deck_id) values ("Friends with benefits.", 2);
insert into white_card (text,deck_id) values ("Teaching a robot to love.", 2);
insert into white_card (text,deck_id) values ("Women's suffrage.", 2);
insert into white_card (text,deck_id) values ("Me time.", 2);
insert into white_card (text,deck_id) values ("The heart of a child.", 2);
insert into white_card (text,deck_id) values ("Smallpox blankets.", 2);
insert into white_card (text,deck_id) values ("The clitoris.", 2);
insert into white_card (text,deck_id) values ("John Wilkes Booth.", 2);
insert into white_card (text,deck_id) values ("The glass ceiling.", 2);
insert into white_card (text,deck_id) values ("Sarah Palin.", 2);
insert into white_card (text,deck_id) values ("Sexy pillow fights.", 2);
insert into white_card (text,deck_id) values ("Yeast.", 2);
insert into white_card (text,deck_id) values ("Full frontal nudity.", 2);
insert into white_card (text,deck_id) values ("Parting the Red Sea.", 2);
insert into white_card (text,deck_id) values ("A Bop It (TM).", 2);
insert into white_card (text,deck_id) values ("Michael Jackson.", 2);
insert into white_card (text,deck_id) values ("Team-building exercises.", 2);
insert into white_card (text,deck_id) values ("Harry Potter erotica.", 2);
insert into white_card (text,deck_id) values ("Authentic Mexican cuisine.", 2);
insert into white_card (text,deck_id) values ("Frolicking.", 2);
insert into white_card (text,deck_id) values ("Sexting.", 2);
insert into white_card (text,deck_id) values ("Grandma.", 2);
insert into white_card (text,deck_id) values ("Not giving a shit about the Third World.", 2);
insert into white_card (text,deck_id) values ("Licking things to claim them as your own.", 2);
insert into white_card (text,deck_id) values ("Genghis Khan.", 2);
insert into white_card (text,deck_id) values ("The hardworking Mexican.", 2);
insert into white_card (text,deck_id) values ("RoboCop.", 2);
insert into white_card (text,deck_id) values ("My relationship status.", 2);
insert into white_card (text,deck_id) values ("Scrubbing under the folds.", 2);
insert into white_card (text,deck_id) values ("Porn Stars.", 2);
insert into white_card (text,deck_id) values ("Horse meat.", 2);
insert into white_card (text,deck_id) values ("Sunshine and rainbows.", 2);
insert into white_card (text,deck_id) values ("Expecting a burp and vomiting on the floor.", 2);
insert into white_card (text,deck_id) values ("Barack Obama.", 2);
insert into white_card (text,deck_id) values ("Spontaneous human combustion.", 2);
insert into white_card (text,deck_id) values ("Natural selection.", 2);
insert into white_card (text,deck_id) values ("Mouth herpes.", 2);
insert into white_card (text,deck_id) values ("Flash flooding.", 2);
insert into white_card (text,deck_id) values ("Goblins.", 2);
insert into white_card (text,deck_id) values ("A monkey smoking a cigar.", 2);
insert into white_card (text,deck_id) values ("Spectacular abs.", 2);
insert into white_card (text,deck_id) values ("A good sniff.", 2);
insert into white_card (text,deck_id) values ("Wiping her butt.", 2);
insert into white_card (text,deck_id) values ("The Three-Fifths compromise.", 2);
insert into white_card (text,deck_id) values ("Pedophiles.", 2);
insert into white_card (text,deck_id) values ("Doin' it in the butt.", 2);
insert into white_card (text,deck_id) values ("Being fabulous.", 2);
insert into white_card (text,deck_id) values ("Mathletes.", 2);
insert into white_card (text,deck_id) values ("Wearing underwear inside-out to avoid doing laundry.", 2);
insert into white_card (text,deck_id) values ("Nipple blades.", 2);
insert into white_card (text,deck_id) values ("An M. Night Shyamalan plot twist.", 2);
insert into white_card (text,deck_id) values ("A bag of magic beans.", 2);
insert into white_card (text,deck_id) values ("Vigorous jazz hands.", 2);
insert into white_card (text,deck_id) values ("A defective condom.", 2);
insert into white_card (text,deck_id) values ("Skeletor.", 2);
insert into white_card (text,deck_id) values ("Vikings.", 2);
insert into white_card (text,deck_id) values ("Leaving an awkward voicemail.", 2);
insert into white_card (text,deck_id) values ("Teenage pregnancy.", 2);
insert into white_card (text,deck_id) values ("Dead parents.", 2);
insert into white_card (text,deck_id) values ("Hot cheese.", 2);
insert into white_card (text,deck_id) values ("My sex life.", 2);
insert into white_card (text,deck_id) values ("A mopey zoo lion.", 2);
insert into white_card (text,deck_id) values ("Assless chaps.", 2);
insert into white_card (text,deck_id) values ("Riding off into the sunset.", 2);
insert into white_card (text,deck_id) values ("Lance Armstrong's missing testicle.", 2);
insert into white_card (text,deck_id) values ("Sweet, sweet vengeance.", 2);
insert into white_card (text,deck_id) values ("Genital piercings.", 2);
insert into white_card (text,deck_id) values ("Keg stands.", 2);
insert into white_card (text,deck_id) values ("Darth Vader.", 2);
insert into white_card (text,deck_id) values ("Viagra (C).", 2);
insert into white_card (text,deck_id) values ("Necrophilia.", 2);
insert into white_card (text,deck_id) values ("A really cool hat.", 2);
insert into white_card (text,deck_id) values ("Toni Morrison's vagina.", 2);
insert into white_card (text,deck_id) values ("An Oedipus complex.", 2);
insert into white_card (text,deck_id) values ("The Tempur-Pedic (C) Swedish Sleep System (TM).", 2);
insert into white_card (text,deck_id) values ("Preteens.", 2);
insert into white_card (text,deck_id) values ("Dick fingers.", 2);
insert into white_card (text,deck_id) values ("A cooler full of organs.", 2);
insert into white_card (text,deck_id) values ("Shapeshifters.", 2);
insert into white_card (text,deck_id) values ("The Care Bear Stare.", 2);
insert into white_card (text,deck_id) values ("Erectile dysfunction.", 2);
insert into white_card (text,deck_id) values ("Keanu Reeves.", 2);
insert into white_card (text,deck_id) values ("The Virginia Tech Massacre.", 2);
insert into white_card (text,deck_id) values ("The Underground Railroad.", 2);
insert into white_card (text,deck_id) values ("The chronic.", 2);
insert into white_card (text,deck_id) values ("Queefing.", 2);
insert into white_card (text,deck_id) values ("Heartwarming orphans.", 2);
insert into white_card (text,deck_id) values ("A thermonuclear detonation.", 2);
insert into white_card (text,deck_id) values ("Cheating in the Special Olympics.", 2);
insert into white_card (text,deck_id) values ("Tangled Slinkys.", 2);
insert into white_card (text,deck_id) values ("A moment of silence.", 2);
insert into white_card (text,deck_id) values ("Civilian casualties.", 2);
insert into white_card (text,deck_id) values ("Catapults.", 2);
insert into white_card (text,deck_id) values ("Sharing needles.", 2);
insert into white_card (text,deck_id) values ("Ethnic cleansing.", 2);
insert into white_card (text,deck_id) values ("Emotions.", 2);
insert into white_card (text,deck_id) values ("Children on leashes.", 2);
insert into white_card (text,deck_id) values ("Balls.", 2);
insert into white_card (text,deck_id) values ("Homeless people.", 2);
insert into white_card (text,deck_id) values ("Eating all of the cookies before the AIDS bake-sale.", 2);
insert into white_card (text,deck_id) values ("Old-people smell.", 2);
insert into white_card (text,deck_id) values ("Farting and walking away.", 2);
insert into white_card (text,deck_id) values ("The inevitable heat death of the universe.", 2);
insert into white_card (text,deck_id) values ("The violation of our most basic human rights.", 2);
insert into white_card (text,deck_id) values ("Fingering.", 2);
insert into white_card (text,deck_id) values ("The placenta.", 2);
insert into white_card (text,deck_id) values ("The Rev. Dr. Martin Luther King, Jr.", 2);
insert into white_card (text,deck_id) values ("Leprosy.", 2);
insert into white_card (text,deck_id) values ("Sperm whales.", 2);
insert into white_card (text,deck_id) values ("Multiple stab wounds.", 2);
insert into white_card (text,deck_id) values ("Flightless birds.", 2);
insert into white_card (text,deck_id) values ("Grave robbing.", 2);
insert into white_card (text,deck_id) values ("Home video of Oprah sobbing into a Lean Cuisine (C).", 2);
insert into white_card (text,deck_id) values ("Oompa-Loompas.", 2);
insert into white_card (text,deck_id) values ("A murder most foul.", 2);
insert into white_card (text,deck_id) values ("Tentacle porn.", 2);
insert into white_card (text,deck_id) values ("Daddy issues.", 2);
insert into white_card (text,deck_id) values ("Bill Nye the Science Guy.", 2);
insert into white_card (text,deck_id) values ("Peeing a little bit.", 2);
insert into white_card (text,deck_id) values ("The miracle of childbirth.", 2);
insert into white_card (text,deck_id) values ("Tweeting.", 2);
insert into white_card (text,deck_id) values ("Another goddamn vampire movie.", 2);
insert into white_card (text,deck_id) values ("Britney Spears at 55.", 2);
insert into white_card (text,deck_id) values ("New Age music.", 2);
insert into white_card (text,deck_id) values ("The Make-A-Wish (R) Foundation.", 2);
insert into white_card (text,deck_id) values ("Firing a rifle into the air while balls deep in a squealing hog.", 2);
insert into white_card (text,deck_id) values ("Active listening.", 2);
insert into white_card (text,deck_id) values ("Nicolas Cage.", 2);
insert into white_card (text,deck_id) values ("72 virgins.", 2);
insert into white_card (text,deck_id) values ("Stranger danger.", 2);
insert into white_card (text,deck_id) values ("Hope.", 2);
insert into white_card (text,deck_id) values ("A gassy antelope.", 2);
insert into white_card (text,deck_id) values ("BATMAN!!!", 2);
insert into white_card (text,deck_id) values ("Chivalry.", 2);
insert into white_card (text,deck_id) values ("Passing a kidney stone.", 2);
insert into white_card (text,deck_id) values ("Black people.", 2);
insert into white_card (text,deck_id) values ("Natalie Portman.", 2);
insert into white_card (text,deck_id) values ("A mime having a stroke.", 2);
insert into white_card (text,deck_id) values ("Classist undertones.", 2);
insert into white_card (text,deck_id) values ("Sean Penn.", 2);
insert into white_card (text,deck_id) values ("A mating display.", 2);
insert into white_card (text,deck_id) values ("The Holy Bible.", 2);
insert into white_card (text,deck_id) values ("Hot Pockets (C).", 2);
insert into white_card (text,deck_id) values ("A sad handjob.", 2);
insert into white_card (text,deck_id) values ("Pulling out.", 2);
insert into white_card (text,deck_id) values ("Serfdom.", 2);
insert into white_card (text,deck_id) values ("Pixelated bukkake.", 2);
insert into white_card (text,deck_id) values ("Dropping a chandelier on your enemies and riding the rope up.", 2);
insert into white_card (text,deck_id) values ("Jew-fros.", 2);
insert into white_card (text,deck_id) values ("Waiting 'til marriage.", 2);
insert into white_card (text,deck_id) values ("Euphoria (TM) by Calvin Klein.", 2);
insert into white_card (text,deck_id) values ("The World of Warcraft.", 2);
insert into white_card (text,deck_id) values ("Lunchables (TM).", 2);
insert into white_card (text,deck_id) values ("The Kool-Aid Man.", 2);
insert into white_card (text,deck_id) values ("The Trail of Tears.", 2);
insert into white_card (text,deck_id) values ("Self-loathing.", 2);
insert into white_card (text,deck_id) values ("A falcon with a cap on its head.", 2);
insert into white_card (text,deck_id) values ("Historically black colleges.", 2);
insert into white_card (text,deck_id) values ("Not reciprocating oral sex.", 2);
insert into white_card (text,deck_id) values ("Global warming.", 2);
insert into white_card (text,deck_id) values ("Ghosts.", 2);
insert into white_card (text,deck_id) values ("World peace.", 2);
insert into white_card (text,deck_id) values ("A can of whoop-ass.", 2);
insert into white_card (text,deck_id) values ("The Dance of the Sugar Plum Fairy.", 2);
insert into white_card (text,deck_id) values ("A zesty breakfast burrito.", 2);
insert into white_card (text,deck_id) values ("Switching to Geico (R).", 2);
insert into white_card (text,deck_id) values ("Aaron Burr.", 2);
insert into white_card (text,deck_id) values ("Picking up girls at the abortion clinic.", 2);
insert into white_card (text,deck_id) values ("Land mines.", 2);
insert into white_card (text,deck_id) values ("Former President George W. Bush.", 2);
insert into white_card (text,deck_id) values ("Geese.", 2);
insert into white_card (text,deck_id) values ("Mutually-assured destruction.", 2);
insert into white_card (text,deck_id) values ("College.", 2);
insert into white_card (text,deck_id) values ("Date rape.", 2);
insert into white_card (text,deck_id) values ("Bling.", 2);
insert into white_card (text,deck_id) values ("A gentle caress of the inner thigh.", 2);
insert into white_card (text,deck_id) values ("A time travel paradox.", 2);
insert into white_card (text,deck_id) values ("Seppuku.", 2);
insert into white_card (text,deck_id) values ("Poor life choices.", 2);
insert into white_card (text,deck_id) values ("Waking up half-naked in a Denny's parking lot.", 2);
insert into white_card (text,deck_id) values ("Italians.", 2);
insert into white_card (text,deck_id) values ("GoGurt (R).", 2);
insert into white_card (text,deck_id) values ("Finger painting.", 2);
insert into white_card (text,deck_id) values ("Robert Downey, Jr.", 2);
insert into white_card (text,deck_id) values ("My soul.", 2);
insert into white_card (text,deck_id) values ("Smegma.", 2);
insert into white_card (text,deck_id) values ("Embryonic stem cells.", 2);
insert into white_card (text,deck_id) values ("The South.", 2);
insert into white_card (text,deck_id) values ("Christopher Walken.", 2);
insert into white_card (text,deck_id) values ("Gloryholes.", 2);
insert into white_card (text,deck_id) values ("Pretending to care.", 2);
insert into white_card (text,deck_id) values ("Public ridicule.", 2);
insert into white_card (text,deck_id) values ("A tiny horse.", 2);
insert into white_card (text,deck_id) values ("Arnold Schwarzenegger.", 2);
insert into white_card (text,deck_id) values ("A stray pube.", 2);
insert into white_card (text,deck_id) values ("Jerking off into a pool of children's tears.", 2);
insert into white_card (text,deck_id) values ("Child abuse.", 2);
insert into white_card (text,deck_id) values ("Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.", 2);
insert into white_card (text,deck_id) values ("Menstruation.", 2);
insert into white_card (text,deck_id) values ("A sassy black woman.", 2);
insert into white_card (text,deck_id) values ("Re-gifting.", 2);
insert into white_card (text,deck_id) values ("Penis envy.", 2);
insert into white_card (text,deck_id) values ("A sausage festival.", 2);
insert into white_card (text,deck_id) values ("Getting really high.", 2);
insert into white_card (text,deck_id) values ("Drinking alone.", 2);
insert into white_card (text,deck_id) values ("Too much hair gel.", 2);
insert into white_card (text,deck_id) values ("Hulk Hogan.", 2);
insert into white_card (text,deck_id) values ("Overcompensation.", 2);
insert into white_card (text,deck_id) values ("Foreskin.", 2);
insert into white_card (text,deck_id) values ("Free samples.", 2);
insert into white_card (text,deck_id) values ("Shaquille O'Neal's acting career.", 2);
insert into white_card (text,deck_id) values ("Five-Dollar Footlongs (TM).", 2);
insert into white_card (text,deck_id) values ("Whipping it out.", 2);
insert into white_card (text,deck_id) values ("A snapping turtle biting the tip of your penis.", 2);
insert into white_card (text,deck_id) values ("Muhammad (Praise Be Unto Him).", 2);
insert into white_card (text,deck_id) values ("Half-assed foreplay.", 2);
insert into white_card (text,deck_id) values ("Dental dams.", 2);
insert into white_card (text,deck_id) values ("Being a dick to children.", 2);
insert into white_card (text,deck_id) values ("Famine.", 2);
insert into white_card (text,deck_id) values ("Chainsaws for hands.", 2);
insert into white_card (text,deck_id) values ("A gypsy curse.", 2);
insert into white_card (text,deck_id) values ("AXE Body Spray.", 2);
insert into white_card (text,deck_id) values ("The Force.", 2);
insert into white_card (text,deck_id) values ("Explosions.", 2);
insert into white_card (text,deck_id) values ("Cybernetic enhancements.", 2);
insert into white_card (text,deck_id) values ("Customer service representatives.", 2);
insert into white_card (text,deck_id) values ("White privilege.", 2);
insert into white_card (text,deck_id) values ("Gandhi.", 2);
insert into white_card (text,deck_id) values ("Road head.", 2);
insert into white_card (text,deck_id) values ("God.", 2);
insert into white_card (text,deck_id) values ("Poorly-timed Holocaust jokes.", 2);
insert into white_card (text,deck_id) values ("8 oz. of sweet Mexican black-tar heroin.", 2);
insert into white_card (text,deck_id) values ("Judge Judy.", 2);
insert into white_card (text,deck_id) values ("The Little Engine That Could.", 2);
insert into white_card (text,deck_id) values ("Altar boys.", 2);
insert into white_card (text,deck_id) values ("Mr. Clean, right behind you.", 2);
insert into white_card (text,deck_id) values ("Vehicular manslaughter.", 2);
insert into white_card (text,deck_id) values ("Dwarf tossing.", 2);
insert into white_card (text,deck_id) values ("Friction.", 2);
insert into white_card (text,deck_id) values ("Lady Gaga.", 2);
insert into white_card (text,deck_id) values ("Scientology.", 2);
insert into white_card (text,deck_id) values ("Justin Bieber.", 2);
insert into white_card (text,deck_id) values ("A death ray.", 2);
insert into white_card (text,deck_id) values ("Vigilante justice.", 2);
insert into white_card (text,deck_id) values ("The Pope.", 2);
insert into white_card (text,deck_id) values ("A sea of troubles.", 2);
insert into white_card (text,deck_id) values ("Alcoholism.", 2);
insert into white_card (text,deck_id) values ("Poor people.", 2);
insert into white_card (text,deck_id) values ("A fetus.", 2);
insert into white_card (text,deck_id) values ("Women in yogurt commercials.", 2);
insert into white_card (text,deck_id) values ("Exactly what you'd expect.", 2);
insert into white_card (text,deck_id) values ("Flesh-eating bacteria.", 2);
insert into white_card (text,deck_id) values ("My genitals.", 2);
insert into white_card (text,deck_id) values ("A balanced breakfast.", 2);
insert into white_card (text,deck_id) values ("Dick Cheney.", 2);
insert into white_card (text,deck_id) values ("Lockjaw.", 2);
insert into white_card (text,deck_id) values ("Natural male enhancement.", 2);
insert into white_card (text,deck_id) values ("Take-backsies.", 2);
insert into white_card (text,deck_id) values ("Winking at old people.", 2);
insert into white_card (text,deck_id) values ("Opposable thumbs.", 2);
insert into white_card (text,deck_id) values ("Flying sex snakes.", 2);
insert into white_card (text,deck_id) values ("Passive-aggressive Post-it notes.", 2);
insert into white_card (text,deck_id) values ("Inappropriate yodeling.", 2);
insert into white_card (text,deck_id) values ("Golden showers.", 2);
insert into white_card (text,deck_id) values ("Racism.", 2);
insert into white_card (text,deck_id) values ("Copping a feel.", 2);
insert into white_card (text,deck_id) values ("Auschwitz.", 2);
insert into white_card (text,deck_id) values ("Elderly Japanese men.", 2);
insert into white_card (text,deck_id) values ("Raping and pillaging.", 2);
insert into white_card (text,deck_id) values ("Kids with ass cancer.", 2);
insert into white_card (text,deck_id) values ("Pictures of boobs.", 2);
insert into white_card (text,deck_id) values ("The homosexual agenda.", 2);
insert into white_card (text,deck_id) values ("A homoerotic volleyball montage.", 2);
insert into white_card (text,deck_id) values ("Sexual tension.", 2);
insert into white_card (text,deck_id) values ("Hurricane Katrina.", 2);
insert into white_card (text,deck_id) values ("Fiery poops.", 2);
insert into white_card (text,deck_id) values ("Science.", 2);
insert into white_card (text,deck_id) values ("Dry heaving.", 2);
insert into white_card (text,deck_id) values ("Cards Against Humanity.", 2);
insert into white_card (text,deck_id) values ("Fancy Feast (C).", 2);
insert into white_card (text,deck_id) values ("A bleached asshole.", 2);
insert into white_card (text,deck_id) values ("Lumberjack fantasies.", 2);
insert into white_card (text,deck_id) values ("American Gladiators.", 2);
insert into white_card (text,deck_id) values ("Autocannibalism.", 2);
insert into white_card (text,deck_id) values ("Sean Connery.", 2);
insert into white_card (text,deck_id) values ("William Shatner.", 2);
insert into white_card (text,deck_id) values ("Domino's (TM) Oreo (TM) Dessert Pizza.", 2);
insert into white_card (text,deck_id) values ("An asymmetric boob job.", 2);
insert into white_card (text,deck_id) values ("Centaurs.", 2);
insert into white_card (text,deck_id) values ("A micropenis.", 2);
insert into white_card (text,deck_id) values ("Asians who aren't good at math.", 2);
insert into white_card (text,deck_id) values ("The milk man.", 2);
insert into white_card (text,deck_id) values ("Waterboarding.", 2);
insert into white_card (text,deck_id) values ("Wifely duties.", 2);
insert into white_card (text,deck_id) values ("Loose lips.", 2);
insert into white_card (text,deck_id) values ("The Blood of Christ.", 2);
insert into white_card (text,deck_id) values ("Actually taking candy from a baby.", 2);
insert into white_card (text,deck_id) values ("The token minority.", 2);
insert into white_card (text,deck_id) values ("Jibber-jabber.", 2);
insert into white_card (text,deck_id) values ("A brain tumor.", 2);
insert into white_card (text,deck_id) values ("Bingeing and purging.", 2);
insert into white_card (text,deck_id) values ("A clandestine butt scratch.", 2);
insert into white_card (text,deck_id) values ("The Chinese gymnastics team.", 2);
insert into white_card (text,deck_id) values ("Prancing.", 2);
insert into white_card (text,deck_id) values ("The Hamburglar.", 2);
insert into white_card (text,deck_id) values ("Police brutality.", 2);
insert into white_card (text,deck_id) values ("Man meat.", 2);
insert into white_card (text,deck_id) values ("Forgetting the Alamo.", 2);
insert into white_card (text,deck_id) values ("Eating the last known bison.", 2);
insert into white_card (text,deck_id) values ("Crystal meth.", 2);
insert into white_card (text,deck_id) values ("Booby-trapping the house to foil burglars.", 2);
insert into white_card (text,deck_id) values ("My inner demons.", 2);
insert into white_card (text,deck_id) values ("Third base.", 2);
insert into white_card (text,deck_id) values ("Soiling oneself.", 2);
insert into white_card (text,deck_id) values ("Laying an egg.", 2);
insert into white_card (text,deck_id) values ("Giving 110%.", 2);
insert into white_card (text,deck_id) values ("Hot people.", 2);
insert into white_card (text,deck_id) values ("Friendly fire.", 2);
insert into white_card (text,deck_id) values ("Count Chocula.", 2);
insert into white_card (text,deck_id) values ("Pac-Man uncontrollably guzzling cum.", 2);
insert into white_card (text,deck_id) values ("Estrogen.", 2);
insert into white_card (text,deck_id) values ("My vagina.", 2);
insert into white_card (text,deck_id) values ("Kanye West.", 2);
insert into white_card (text,deck_id) values ("A robust mongoloid.", 2);
insert into white_card (text,deck_id) values ("The Donald Trump Seal of Approval (TM).", 2);
insert into white_card (text,deck_id) values ("The true meaning of Christmas.", 2);
insert into white_card (text,deck_id) values ("Her Royal Highness, Queen Elizabeth II.", 2);
insert into white_card (text,deck_id) values ("An honest cop with nothing left to lose.", 2);
insert into white_card (text,deck_id) values ("Feeding Rosie O'Donnell.", 2);
insert into white_card (text,deck_id) values ("The Amish.", 2);
insert into white_card (text,deck_id) values ("The terrorists.", 2);
insert into white_card (text,deck_id) values ("When you fart and a little bit comes out.", 2);
insert into white_card (text,deck_id) values ("Pooping back and forth. Forever.", 2);
insert into white_card (text,deck_id) values ("Friends who eat all the snacks.", 2);
insert into white_card (text,deck_id) values ("Cockfights.", 2);
insert into white_card (text,deck_id) values ("Bitches.", 2);
insert into white_card (text,deck_id) values ("Seduction.", 2);
